import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
}

export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs: FaqItem[] = [
    {
      question: 'When should someone schedule an appointment with a cardiologist?',
      answer:
        'You should consult a cardiologist if you experience chest pain, heaviness or tightness on exertion, shortness of breath, sudden palpitations or fluttering in the chest, unexplained fainting spells (syncope), swollen ankles, or consistently high blood pressure readings (>130/80 mmHg). Additionally, individuals with a family history of early heart disease or diabetes should seek proactive preventive screening.',
    },
    {
      question: 'What documents and records should I bring for my first cardiology consultation?',
      answer:
        'Please bring: 1) Past electrocardiogram (ECG) tracings or echocardiography reports; 2) Recent blood tests (lipid profile, HbA1c, kidney function); 3) Complete list of all current medications, dosages, and supplements; 4) Any prior hospital discharge summaries, cardiac catheterization reports, or stent implant identity cards; 5) A 7-day home blood pressure log if you monitor your BP.',
    },
    {
      question: 'How is an ECG performed and is there any discomfort?',
      answer:
        'A 12-lead ECG is a completely painless, non-invasive diagnostic test that takes approximately 5 to 10 minutes. Small adhesive sensor pads (electrodes) are attached to your chest, arms, and legs. They record the natural electrical impulses generated by each heartbeat without sending any electricity into your body.',
    },
    {
      question: 'What is a 2D Doppler Echocardiogram and why might it be recommended?',
      answer:
        'An echocardiogram is a non-invasive ultrasound of your heart. It allows Dr. B. Vijaya Chaitanya to view your heart beating in real time, measure the muscular thickness and pumping strength (Ejection Fraction / EF) of the ventricles, and check whether your heart valves open and close properly without leakage or narrowing.',
    },
    {
      question: 'Can I consult Dr. B. Vijaya Chaitanya for a second opinion on recommended coronary procedures?',
      answer:
        'Yes. Seeking a second opinion is a standard and recommended practice in cardiology, particularly when evaluating coronary angiography films, complex stenting (PCI), or coronary artery bypass surgery (CABG). Dr. Chaitanya provides an objective, guideline-directed review of your coronary anatomy and diagnostic imaging.',
    },
    {
      question: 'How can I prevent heart disease if I have a family history?',
      answer:
        'Genetics increases susceptibility, but aggressive early lifestyle and medical intervention can drastically reduce your risk. We recommend advanced lipid testing (measuring ApoB and Lipoprotein(a)), coronary artery calcium (CAC) scoring, blood pressure optimization, a cardioprotective Mediterranean diet, and structured physical activity.',
    },
  ];

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-20 lg:py-24 bg-slate-50/60 relative">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Pill Badge */}
        <div className="flex justify-center mb-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white border border-slate-200 text-slate-700 text-xs font-semibold uppercase tracking-wider shadow-xs">
            <HelpCircle className="w-3.5 h-3.5 text-cardio-red" />
            <span>Patient FAQs</span>
          </div>
        </div>

        {/* Section Header */}
        <div className="text-center mb-14 space-y-3">
          <h2 className="text-3xl sm:text-4xl font-extrabold font-display text-navy-950 tracking-tight">
            Frequently Asked Questions
          </h2>
          <p className="text-slate-600 text-sm sm:text-base max-w-xl mx-auto">
            Clear, transparent answers regarding cardiology appointments, diagnostic procedures, and preventive care.
          </p>
        </div>

        {/* Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="bg-white rounded-2xl border border-slate-200/90 shadow-glass overflow-hidden transition-all duration-200"
              >
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 font-display font-bold text-navy-950 text-sm sm:text-base hover:text-cardio-red transition-colors"
                >
                  <span>{faq.question}</span>
                  <div
                    className={`w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center shrink-0 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 bg-red-50 text-cardio-red' : 'text-slate-500'
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 pb-6 sm:px-6 sm:pb-6 text-xs sm:text-sm text-slate-600 leading-relaxed border-t border-slate-100 pt-4">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
